name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
          build-essential autoconf automake libtool pkg-config \
          zlib1g-dev libncurses5 libncurses5-dev libsqlite3-dev \
          libgdbm-dev libbz2-dev libffi-dev libssl-dev aidl
        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip sdk.zip -d latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/33.0.2:$PATH" >> $GITHUB_ENV

    - name: Install SDK packages
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        yes | sdkmanager --licenses

    - name: Build APK
      run: buildozer android debug

    - name: Commit APK
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add bin/*.apk
        git commit -m "Add built APK"
        git push origin HEAD:apk-output
