name: Upload Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: echo "Hello GitHub" > test.txt

    - name: Upload file
      uses: actions/upload-artifact@v3
      with:
        name: test-file
        path: test.txt
