name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Accept Android SDK Licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
          build-essential autoconf automake libtool pkg-config \
          zlib1g-dev libncurses5 libncurses5-dev libsqlite3-dev \
          libgdbm-dev libbz2-dev libffi-dev libssl-dev
        pip install --upgrade pip
        pip install cython buildozer

    - name: Build APK
      run: |
        buildozer android debug

   # - name: Upload APK
    #  uses: actions/upload-artifact@v3
     # with:
      #  name: wifi_hack_apk
       # path: bin/*.apk

    - name: Commit APK
      run: |
       git config user.name "github-actions"
       git config user.email "github-actions@github.com"
       git add bin/*.apk
       git commit -m "Add built APK"
       git push origin HEAD:apk-output
