name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
          build-essential autoconf automake libtool pkg-config \
          zlib1g-dev libncurses5 libncurses5-dev libsqlite3-dev \
          libgdbm-dev libbz2-dev libffi-dev libssl-dev
        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk-tools.zip
        unzip sdk-tools.zip
        mv cmdline-tools latest
      env:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Accept Android SDK licenses
      run: yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android SDK packages
      run: |
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Update buildozer.spec to use stable build tools
      run: |
        sed -i 's/^#*android.build_tools_version = .*/android.build_tools_version = 33.0.2/' buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Commit APK
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b apk-output || git checkout apk-output
        git add bin/*.apk || echo "No APK found to commit."
        git commit -m "Add built APK" || echo "Nothing to commit."
        git push origin apk-output
