name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential libssl-dev libffi-dev python3-dev
        sudo apt install -y libncurses5-dev libsqlite3-dev libgdbm-dev libbz2-dev
        sudo apt install -y git zip
        pip install --upgrade pip
        pip install buildozer

    - name: Install Buildozer and SDK/NDK dependencies
      run: |
        buildozer init
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: wifi_connector_apk
        path: bin/wifi_connector-debug.apk
